DIR_DATA = "data"
DIR_GRAPH = "graph"
DIR_PICKLE = "pickle"

FILE_DATA_FRAME = f"{DIR_PICKLE}/tsp_problems_dataframe.pkl"
FILE_OPTIMAL_COSTS = f"{DIR_DATA}/optimal_costs.json"

TIME_TAKEN_PLACEHOLDER = "Time taken to {action}: {length:.5f}s"

SOLUTION_DP = "dp"
SOLUTION_GREEDY = "greedy"
SOLUTION_CHRISTOFIDES = "christofides"
SOLUTION_SIMULATED_ANNEALING_RANDOM_SWAP = "sa-random_swap"
SOLUTION_SIMULATED_ANNEALING_NEAREST_NEIGHBOR_2_OPT = "sa-nn_2_opt"
SOLUTION_SIMULATED_ANNEALING_GREEDY_SWAP = "sa-greedy_swap"
SOLUTION_SIMULATED_ANNEALING_LOGARITHMIC_COOLING_2_OPT = "sa-log_cool_2_opt"
SOLUTION_SIMULATED_ANNEALING_GREEDY_3_OPT = "sa-greedy_3_opt"
SOLUTION_LIN_KERNIGHAN = "lk"
SOLUTION_GENETIC_TOURNAMENT_SELECTION = "ga-tournament"
SOLUTION_GENETIC_ADAPTIVE_MUTATION = "ga-adaptive"
ALL_SOLUTIONS = [
  SOLUTION_DP,
  SOLUTION_GREEDY,
  SOLUTION_CHRISTOFIDES,

  # Simulated annealing
  SOLUTION_SIMULATED_ANNEALING_RANDOM_SWAP,
  SOLUTION_SIMULATED_ANNEALING_NEAREST_NEIGHBOR_2_OPT,
  SOLUTION_SIMULATED_ANNEALING_GREEDY_SWAP,
  SOLUTION_SIMULATED_ANNEALING_LOGARITHMIC_COOLING_2_OPT,
  SOLUTION_SIMULATED_ANNEALING_GREEDY_3_OPT,

  # Genetic
  SOLUTION_GENETIC_TOURNAMENT_SELECTION,
  SOLUTION_GENETIC_ADAPTIVE_MUTATION,

  SOLUTION_LIN_KERNIGHAN,
]
